-- =====================================================
-- ALTER TABLE: Add subject_code column to feedback_forms
-- =====================================================

ALTER TABLE feedback_forms ADD COLUMN IF NOT EXISTS subject_code TEXT;

-- =====================================================
-- NEW TABLE: subjects (master list of all subjects)
-- =====================================================

CREATE TABLE IF NOT EXISTS subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_name TEXT NOT NULL,
    department TEXT NOT NULL,
    semester INTEGER NOT NULL,
    subject_code TEXT NOT NULL,
    subject_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(course_name, subject_code)
);

-- =====================================================
-- SEED: Courses
-- =====================================================

INSERT INTO courses (course_name, department) VALUES
    ('B.Com LLB', 'Law'),
    ('B.Pharma', 'Pharmacy'),
    ('B.Tech Biotechnology', 'Biotechnology'),
    ('B.Tech CSE', 'Computer Science & Engineering'),
    ('BA Economics Hons', 'Arts & Humanities'),
    ('BA English Hons', 'Arts & Humanities'),
    ('BA LLB', 'Law'),
    ('BA Psychology Hons', 'Arts & Humanities'),
    ('BBA LLB', 'Law'),
    ('BSc Hons Chemistry', 'Sciences'),
    ('BSc PCM', 'Sciences'),
    ('BSc ZBC', 'Sciences'),
    ('LLB', 'Law')
ON CONFLICT DO NOTHING;

-- =====================================================
-- SEED: Subjects
-- =====================================================
-- B.Com LLB
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('B.Com LLB', 'Law', 1, 'BCL1016', 'Election law'),
    ('B.Com LLB', 'Law', 1, 'BCL911', 'Forensic Science 2.'),
    ('B.Com LLB', 'Law', 1, 'BCL912', 'Criminology & penology 3.'),
    ('B.Com LLB', 'Law', 1, 'BCL913', 'Competition & Investment Laws 4.'),
    ('B.Com LLB', 'Law', 1, 'BCL914', 'Law related to women & Children 5.')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- B.Pharma
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('B.Pharma', 'Pharmacy', 1, 'BP101T', 'Human Anatomy and Physiology I–'),
    ('B.Pharma', 'Pharmacy', 1, 'BP102T', 'Pharmaceutical Analysis I – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP103T', 'Pharmaceutics I – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP104T', 'Pharmaceutical Inorganic Chemistry –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP105T', 'Communication skills – Theory *'),
    ('B.Pharma', 'Pharmacy', 1, 'BP107P', 'Human Anatomy and Physiology –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP108P', 'Pharmaceutical Analysis I – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP109P', 'Pharmaceutics I – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP110P', 'Pharmaceutical Inorganic Chemistry –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP111P', 'Communication skills – Practical*'),
    ('B.Pharma', 'Pharmacy', 1, 'BP207P', 'Human Anatomy and Physiology'),
    ('B.Pharma', 'Pharmacy', 1, 'BP208P', 'Pharmaceutical Organic'),
    ('B.Pharma', 'Pharmacy', 1, 'BP209P', 'Biochemistry – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP210P', 'Computer Applications in'),
    ('B.Pharma', 'Pharmacy', 1, 'BP305P', 'Pharmaceutical Organic'),
    ('B.Pharma', 'Pharmacy', 1, 'BP306P', 'Physical Pharmaceutics I –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP307P', 'Pharmaceutical Microbiology –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP308P', 'Pharmaceutical Engineering –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP401T', 'Pharmaceutical Organic Chemistry III– Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP402T', 'Medicinal Chemistry I – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP403T', 'Physical Pharmaceutics II – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP404T', 'Pharmacology I – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP405T', 'Pharmacognosy and Phytochemistry I– Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP406P', 'Medicinal Chemistry I – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP407P', 'Physical Pharmaceutics II – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP408P', 'Pharmacology I – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP409P', 'Pharmacognosy and Phytochemistry I – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP501T', 'Medicinal Chemistry II – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP502T', 'Industrial PharmacyI– Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP503T', 'Pharmacology II – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP504T', 'Pharmacognosy and Phytochemistry II– Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP505T', 'Pharmaceutical Jurisprudence – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP506P', 'Industrial PharmacyI – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP507P', 'Pharmacology II – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP508P', 'Pharmacognosy and Phytochemistry II –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP607P', 'Medicinal chemistry III –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP608P', 'Pharmacology III – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP609P', 'Herbal Drug Technology –'),
    ('B.Pharma', 'Pharmacy', 1, 'BP701T', 'Instrumental Methods of Analysis – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP702T', 'Industrial PharmacyII – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP703T', 'Pharmacy Practice – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP704T', 'Novel Drug Delivery System – Theory'),
    ('B.Pharma', 'Pharmacy', 1, 'BP705P', 'Instrumental Methods of Analysis – Practical'),
    ('B.Pharma', 'Pharmacy', 1, 'BP801T', 'Biostatistics and Research Methodology'),
    ('B.Pharma', 'Pharmacy', 1, 'BP802T', 'Social and Preventive Pharmacy')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- B.Tech Biotechnology
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BAS101', 'Physics BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BAS151', 'Physics Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BAS201', 'Chemistry BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BAS251', 'Chemistry Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT101', 'Elementary Mathematics I BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT102', 'Remedial Biology I BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT103', 'Basic Electrical Engineering ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT104', 'Introduction to Biotechnology ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT105', 'Sports and Yoga AUC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT153', 'Basic Electrical Engineering Lab ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT201', 'Elementary Mathematics II BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT202', 'Remedial Biology II BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BBT203', 'Advanced Biotechnology ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT301', 'Food Biotechnology HSS'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT302', 'Biostatistics BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT303', 'Microbiology BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT304', 'Biochemistry BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT305', 'Cell Biology BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT306', 'Analytical Techniques PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT307', 'Plant Biology BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT353', 'Microbiology Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT354', 'Biochemistry Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT355', 'Cell Biology Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT356', 'Analytical Techniques Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT401', 'Molecular Biology PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT402', 'Bioprocess Engineering PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT403', 'Immunology & Immunotechnology PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT404', 'rDNA Technology PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT405', 'Bioinformatics & Computational Biology'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT406', 'Bioseparation Engineering PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT407', 'Engineering Economics PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT408', 'Environmental Science AUC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT451', 'Molecular Biology Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT452', 'Bioprocess Engineering lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT453', 'Immunology & Immunotechnology lab'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT454', 'rDNA Technology lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'BBT455', 'Bioinformatics & Computational Biology lab'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT501', 'Environmental Biotechnology'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT502', 'Genetic Engineering BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT503', 'Animal Biotechnology PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT504', 'Bioprocess Engineering PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT505', 'Genomics and Proteomics'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT506', 'Molecular Dynamics & Bioenergetics'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT551', 'Environmental Biotechnology Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT552', 'Bioprocess Engineering Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT553', 'Genomics and Proteomics Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT601', 'Plant Biotechnology PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT602', 'Intellectual Property Right, Bioethics and Biosafety'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT603', 'Bioreactor: Design and Analysis ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT604', 'Downstream Processing ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT605', 'Advancements in Applied Biotechnology'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT606', 'Project Management and Paper Writing PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT651', 'Plant Biotechnology Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT652', 'Downstream Processing Lab PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'BBT653', 'Advancements in Applied Biotechnology Lab'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT701', 'Structural Biology HSS'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT702', 'Bioentrepreneurship BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT703', 'Medical Biotechnology BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT704', 'Biosensors BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT705', 'Vaccine Technology BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT706', 'Biophysics PCC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT751', 'Structural Biology Lab BSC'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT752', 'Internal Project PS'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'BBT753', 'Seminar PS'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BCS201', 'Programming for Problem Solving ESC'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'BCS251', 'Programming for Problem Solving Lab'),
    ('B.Tech Biotechnology', 'Biotechnology', 3, 'GP401', 'General Proficiency -'),
    ('B.Tech Biotechnology', 'Biotechnology', 5, 'GP501', 'General Proficiency -'),
    ('B.Tech Biotechnology', 'Biotechnology', 7, 'GP701', 'General Proficiency -'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'HAS201', 'English HSS'),
    ('B.Tech Biotechnology', 'Biotechnology', 1, 'HAS251', 'English Lab HSS')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- B.Tech CSE
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BAS101', 'Physics'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BAS102', 'Mathematics-I'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BAS151', 'Physics Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BAS251', 'Chemistry Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BAS301', 'Mathematics III'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BAS701', 'Genetics Science'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS051', 'Principles of Programming'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS052', 'Fuzzy Logic'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS053', 'Multimedia Systems'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS054', 'Soft Computing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS055', 'Discrete Structures'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS061', 'Software Testing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS062', 'Graph Theory'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS063', 'System Programming'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS065', 'Linux Administration'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS066', 'Software Project'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS067', 'Pattern Recognition'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS068', 'Parallel Algorithms'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS069', 'Internet Technology'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS071', 'Embedded and Real Time Systems'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS072', 'Data Compression'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS073', 'Neural Network'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS074', 'Android Operating System'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS075', 'Client Server Computing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS076', 'Distributed Database'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS077', 'Software Quality Management'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS078', 'Simulation and Modeling'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS079', 'Unix and Shell Programming'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS080', 'Digital Image Processing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS081', 'Computational Geometry'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS082', 'Computational Complexity'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS083', 'IT in Forensics Science'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS084', 'Advanced Computer Network'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS085', 'Big Data Analysis'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS086', 'Advanced Computer Architecture'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS087', 'Artificial Intelligence and Expert Systems'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS088', 'Data Warehouse and Mining'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS089', 'Distributed System'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS090', 'IT Workshop (Sci Lab/ MATLAB)'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS091', 'Cryptography and Network Security'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS092', '.NET Framework'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS093', 'Mobile Computing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS094', 'Machine Learning'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS095', 'Speech and Natural Language Processing'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BCS101', 'Introduction to Computers'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BCS151', 'Introduction to computers Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS301', 'Data Structures'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS302', 'IT Infrastructure Management'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS303', 'Digital Electronics'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS304', 'Python'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS351', 'Data structures Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS352', 'IT Infrastructure Management Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS353', 'Digital Electronics Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS354', 'Python Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS401', 'Computer Organization & Architecture'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS402', 'Design and Analysis of Algorithms'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS403', 'Operating Systems'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS404', 'Software Engineering'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS451', 'Computer Organization & Architecture Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS452', 'Design and Analysis of Algorithms Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BCS453', 'Operating System Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS501', 'Formal Language and Automata Theory'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS502', 'Database Management Systems'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS503', 'Java Programming'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS505', 'Introduction to Microprocessor'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS552', 'DBMS Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS553', 'Java Programming'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS601', 'Computer Network'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS602', 'Compiler Design'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS651', 'Computer Network Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BCS655', 'Compiler Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BCS754', 'Industrial Training Viva'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BEC101', 'Emerging Domain in Electronics Engineering'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BEE201', 'Basic Electrical Engineering'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'BMC001', 'Environmental Science'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BMC003', 'Constitution Of India'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BME101', 'Engineering Graphics and Design'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BME151', 'Engineering Graphics and Design Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BME201', 'Engineering Graphics and Design'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BME251', 'Engineering Graphics and Design'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'BME252', 'Basic Electrical Engineering Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BOE601', 'Total Quality Management'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BOE602', 'Human Computer Interaction'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BOE603', 'Enrepreneurship Development'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BOE604', 'Non-Conventional Energy Resources'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'BOE605', 'Operational Research'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BOE701', 'Soft Skills and Interpersonal Communication'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BOE702', 'Cyber Law and Ethics'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BOE703', 'Human Resource Development and Management'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BOE704', 'Product Development'),
    ('B.Tech CSE', 'Computer Science & Engineering', 7, 'BOE705', 'Queuing Theory and Modelling'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'HAS201', 'English'),
    ('B.Tech CSE', 'Computer Science & Engineering', 1, 'HAS251', 'English Lab'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'HAS303', 'Industrial Psychology'),
    ('B.Tech CSE', 'Computer Science & Engineering', 3, 'HAS402', 'Industrial Sociology'),
    ('B.Tech CSE', 'Computer Science & Engineering', 5, 'HAS501', 'Professional Law And Ethics')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BA Economics Hons
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BA Economics Hons', 'Arts & Humanities', 5, 'DSE51', 'DSE-1'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'DSE52', 'DSE-2'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'DSE61', 'DSE-3'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'DSE62', 'DSE-4'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEA201', 'Environmental Science'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEC101', 'Mathematical Methods for Economics'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEC102', 'Introductory Micro -economics'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEC201', 'Mathematical Methods for Economics'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEC202', 'Introductory Macro- economics'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC301', 'Intermediate Microeconomics I'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC302', 'Intermediate Macroeconomics I'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC303', 'Statistical Methods for Economics'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC401', 'Intermediate Microeconomics II'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC402', 'Intermediate Macroeconomics II'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HEC403', 'Introductory Econometrics'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HEC501', 'Indian Economy I'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HEC502', 'Development Economics I'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED051', 'Game Theory'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED052', 'Public Economics'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED053', 'Financial Economics'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED054', 'Applied Econometrics'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED055', 'Economic History of India (1857-1947)'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED056', 'Political Economy I'),
    ('BA Economics Hons', 'Arts & Humanities', 5, 'HED057', 'International Trade'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEG101', 'Introductory Microeconomics'),
    ('BA Economics Hons', 'Arts & Humanities', 1, 'HEG201', 'Introductory Macroeconomics'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HES301', 'Data Analysis'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HES401', 'Research Methodology'),
    ('BA Economics Hons', 'Arts & Humanities', 3, 'HES402', 'Contemporary Economic Issues')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BA English Hons
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BA English Hons', 'Arts & Humanities', 1, 'BAEN101', 'Indian Classical Literature')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BA LLB
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BA LLB', 'Law', 1, 'BAL1016', 'Election law'),
    ('BA LLB', 'Law', 1, 'BAL911', 'Forensic Science 2.'),
    ('BA LLB', 'Law', 1, 'BAL912', 'Criminology & penology 3.'),
    ('BA LLB', 'Law', 1, 'BAL913', 'Competition & Investment Laws 4.'),
    ('BA LLB', 'Law', 1, 'BAL914', 'Law related to women & Children 5.')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BA Psychology Hons
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPA101', 'Environmental Science'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPA201', 'English Communication'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC101', 'Introduction to Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC102', 'Statistical Methods for Psychological Research-I'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC151', 'Lab on Introduction to Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC201', 'Biopsychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC202', 'Psychology of Individual Differences'),
    ('BA Psychology Hons', 'Arts & Humanities', 1, 'HPC251', 'Lab on Psychology of Individual'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC301', 'Development of Psychological'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC302', 'Psychological Research'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC303', 'Social Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC351', 'Lab on Psychological Research'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC401', 'Understanding Psychological'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC402', 'Statistical Methods for Psychological Research-II'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC403', 'Applied Social Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 3, 'HPC451', 'Lab on Applied Social'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC501', 'Understanding and Dealing with'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC502', 'Developmental Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC551', 'Lab on Psychological Disorders'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC552', 'Lab on Developmental Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC601', 'Organizational Behavior'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC602', 'Counseling Psychology'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC651', 'Lab on Organizational Behavior'),
    ('BA Psychology Hons', 'Arts & Humanities', 5, 'HPC652', 'Lab on Counseling Psychology')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BBA LLB
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BBA LLB', 'Law', 1, 'BBL1016', 'Election law'),
    ('BBA LLB', 'Law', 1, 'BBL911', 'Forensic Science 2.'),
    ('BBA LLB', 'Law', 1, 'BBL912', 'Criminology & penology 3.'),
    ('BBA LLB', 'Law', 1, 'BBL913', 'Competition & Investment Laws 4.'),
    ('BBA LLB', 'Law', 1, 'BBL914', 'Law related to women & Children 5.')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BSc Hons Chemistry
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC25I', 'Chemistry Lab-II'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC302', 'Physical Chemistry-ll J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC402', 'Organic Chemistry-III J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC45I', 'Chemistry Lab-IV'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC502', ')rganic Chemistry-lV J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC504', 'Biochemistry and Environmental Chemistry aJ'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC552', 'Physical &Biochemistry and Environmental Chemistry Lab'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC603', 'Physical Chemistry-lV J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC604', '{pplication of Computers in Chemistry'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHC652', 'Physical Chemistry & Applications of Computers in Chemistry Lab'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHCI02', 'Organic Chemistry-I .,'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHM20I', 'Vector Calculus J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHM25I', 't,ab Work-ll'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHM35I', 'Lab Work-lII'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHM45I', 'Lab Work-lV'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BHP302', 'Semiconductor Physics J'),
    ('BSc Hons Chemistry', 'Sciences', 1, 'BTIC35I', 'Chemistry Lab-lll {}')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BSc PCM
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BSc PCM', 'Sciences', 5, 'CMR502', 'Dse,.2M'),
    ('BSc PCM', 'Sciences', 5, 'CMR551', 'Math lab-l'),
    ('BSc PCM', 'Sciences', 5, 'CMR651', 'Math Lab-ll'),
    ('BSc PCM', 'Sciences', 3, 'CPR35I', 'Physics (EM)Lab - III'),
    ('BSc PCM', 'Sciences', 5, 'CPR651', 'Inorganic Chemistry Lab'),
    ('BSc PCM', 'Sciences', 5, 'CPR65I', 'Physics Lab-VI'),
    ('BSc PCM', 'Sciences', 5, 'CSE60I', 'SEC-4'),
    ('BSc PCM', 'Sciences', 3, 'CSR351', 'Physical Chemistry Lab -ilI'),
    ('BSc PCM', 'Sciences', 5, 'CSR551', 'Organic Chemistry Lab'),
    ('BSc PCM', 'Sciences', 5, 'CSR651', 'Physical ChemistrY lab Inorganic Chemistry'),
    ('BSc PCM', 'Sciences', 5, 'DSE18', 'Csr6Oi Dse-2C'),
    ('BSc PCM', 'Sciences', 5, 'DSE28', 'Cpr6O2 Dse.3P'),
    ('BSc PCM', 'Sciences', 1, 'VOI001', 'Introduction of MS – Office (MS Word, MS Excel, MS Power Point)'),
    ('BSc PCM', 'Sciences', 1, 'VOI002', 'Mathematical Software- MATLAB, SPSS, Mathematica, Maple, LaTeX (Anyone)'),
    ('BSc PCM', 'Sciences', 1, 'VOI003', 'Chemical Technology & Society Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI004', 'Pharmaceutical Chemistry Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI005', 'Aquarium and fish keeping Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI006', 'Apiculture Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI007', 'Sericulture Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI008', 'Retail Management Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI011', 'Ethnobotany Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI012', 'Intellectual Property Rights (IPR) Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI015', 'Banking and Finance Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI016', 'Basic Computer Skill Independent'),
    ('BSc PCM', 'Sciences', 1, 'VOI017', 'Comprehensive Program On Stock Market'),
    ('BSc PCM', 'Sciences', 1, 'VPA101', 'Handling of Electrical and Electronic Products. Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPB101', 'Yoga Science Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPC101', 'Multimedia and Animation Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPD101', 'Agribusiness Management Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPE101', 'COMPUTER OFFICE MANAGEMENT Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPF101', 'Public Relation officer Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPG101', 'TECHNOLOGY ADVANCEMENT BOOTCAMP Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPH101', 'Electronics Technician Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPI101', 'Domestic Data Entry Operator Progressive'),
    ('BSc PCM', 'Sciences', 1, 'VPJ101', 'Yoga Instructor Progressive')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- BSc ZBC
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('BSc ZBC', 'Sciences', 5, 'CBT552', 'Botany lab-Vl'),
    ('BSc ZBC', 'Sciences', 5, 'CBT652', 'Botanv lab-VII'),
    ('BSc ZBC', 'Sciences', 5, 'CSE602', 'SEC-4'),
    ('BSc ZBC', 'Sciences', 3, 'CSR351', 'Genetics and Evolutionary Biology Ecology and Plant Physiology'),
    ('BSc ZBC', 'Sciences', 5, 'CSR551', 'Chemistry lab-V :'),
    ('BSc ZBC', 'Sciences', 5, 'CSR55I', 'Chemistry lab-V DSE-rB(P)'),
    ('BSc ZBC', 'Sciences', 5, 'CSR602', 'Dse-3C J'),
    ('BSc ZBC', 'Sciences', 5, 'CSR651', 'Chemistry lab-Vl'),
    ('BSc ZBC', 'Sciences', 5, 'CSR652', 'Chemistry lab-VII'),
    ('BSc ZBC', 'Sciences', 3, 'CZT451', 'Botany lab-lV'),
    ('BSc ZBC', 'Sciences', 5, 'CZT551', 'Zoology lab-V'),
    ('BSc ZBC', 'Sciences', 5, 'CZT552', 'Zoology lab-Vl'),
    ('BSc ZBC', 'Sciences', 5, 'CZT55I', 'Zoology lab-V'),
    ('BSc ZBC', 'Sciences', 5, 'CZT651', 'Zoology lab-VII'),
    ('BSc ZBC', 'Sciences', 5, 'CZT65I', 'Zoology lab-VlI'),
    ('BSc ZBC', 'Sciences', 5, 'DSE28', 'aJ I'),
    ('BSc ZBC', 'Sciences', 5, 'DSE38', 'Csr6O2 Dse-3C'),
    ('BSc ZBC', 'Sciences', 1, 'VOI001', 'Introduction of MS – Office (MS Word, MS Excel, MS Power Point)'),
    ('BSc ZBC', 'Sciences', 1, 'VOI002', 'Mathematical Software- MATLAB, SPSS, Mathematica, Maple, LaTeX (Anyone)'),
    ('BSc ZBC', 'Sciences', 1, 'VOI003', 'Chemical Technology & Society Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI004', 'Pharmaceutical Chemistry Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI005', 'Aquarium and fish keeping Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI006', 'Apiculture Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI007', 'Sericulture Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI008', 'Retail Management Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI011', 'Ethnobotany Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI012', 'Intellectual Property Rights (IPR) Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI015', 'Banking and Finance Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI016', 'Basic Computer Skill Independent'),
    ('BSc ZBC', 'Sciences', 1, 'VOI017', 'Comprehensive Program On Stock Market'),
    ('BSc ZBC', 'Sciences', 1, 'VPA101', 'Handling of Electrical and Electronic Products. Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPB101', 'Yoga Science Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPC101', 'Multimedia and Animation Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPD101', 'Agribusiness Management Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPE101', 'COMPUTER OFFICE MANAGEMENT Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPF101', 'Public Relation officer Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPG101', 'TECHNOLOGY ADVANCEMENT BOOTCAMP Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPH101', 'Electronics Technician Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPI101', 'Domestic Data Entry Operator Progressive'),
    ('BSc ZBC', 'Sciences', 1, 'VPJ101', 'Yoga Instructor Progressive')
ON CONFLICT (course_name, subject_code) DO NOTHING;

-- LLB
INSERT INTO subjects (course_name, department, semester, subject_code, subject_name) VALUES
    ('LLB', 'Law', 1, 'LAW506', 'Human Rights & Practice 4.'),
    ('LLB', 'Law', 1, 'LAW602', 'Information Technology Laws 5.')
ON CONFLICT (course_name, subject_code) DO NOTHING;
